name: Build
on: [pull_request, push]
jobs:
  build:
    strategy:
      matrix:
        java: [17, 18]
        os: [ubuntu-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Cache Dependencies
        uses: actions/cache@v3
        with:
          path: |
           ~/.gradle/caches
           ~/.gradle/loom-cache
           ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/gradle-wrapper.properties') }}
          restore-keys: |
            ${{ runner.os }}-gradle-
      - name: Checkout Repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Setup JDK ${{ matrix.java }}
        uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: ${{ matrix.java }}
      - name: Validate Gradle Wrapper
        uses: gradle/wrapper-validation-action@v1
      - name: Build
        run: ./gradlew build
      - name: Capture Build Artifacts
        #if: ${{ runner.os == 'Linux' && matrix.java == '17' }} # Only upload artifacts from Linux
        uses: actions/upload-artifact@v3
        with:
          name: WilderWild-Artifacts-${{ steps.ref.outputs.branch }}
          path: build/libs/
